apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
    .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJkR0ZzWVhOaVpXdHZkanBuYUhCZlZrUkVRVmx0Y0RCM1JuUllNbWMxZEdSUlJXdzNhWGxQYkVGemNHMXlNbVJKUW05RSJ9fX0=
type: kubernetes.io/dockerconfigjson
